theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 前端开发工程师

# 对你自己的简洁描述
description: 爱生活，爱编程，爱学习。

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: 祁贺（henry）

# 你的联系方式
phone: 18888888888

# 你的邮箱
email: 2141688730@qq.com

# 你目前的住址
address: 中国江苏

# 你毕业院校
school: 郑州大学

# 你的专业
profession: 能源工程

# 你的学位
degree: 本科

# 你获得过的证书或奖励
credential: 计算机二级
